export const FETCH_APIDATA_PENDING = 'FETCH_APIDATA_PENDING';
export const FETCH_APIDATA_SUCCESS = 'FETCH_APIDATA_SUCCESS';
export const FETCH_APIDATA_FAILD  = 'FETCH_APIDATA_FAILD';
export const TRANSFORM_DATA = 'TRANSFORM_DATA';